inherit_gem:
  aaf-gumboot: aaf-rubocop.yml
  syntax_tree: config/rubocop.yml

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  # - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/**
    - db/**/*

Layout/LineLength:
  Max: 120

Style/StderrPuts:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_sql
    - find_by_identifying_attribute

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/QuotedSymbols:
  Enabled: true
  EnforcedStyle: single_quotes
