inherit_gem:
  syntax_tree: config/rubocop.yml

require:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  # TODO: turning this on breaks alot of tests. must be the given -> let change
  # - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - bin/**
    - db/**/*

Layout/LineLength:
  Max: 120

Rails/DynamicFindBy:
  Whitelist:
    - find_by_sql
    - find_by_identifying_attribute
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/QuotedSymbols:
  Enabled: true
  EnforcedStyle: single_quotes

Metrics/ClassLength:
  CountAsOne: ['heredoc', 'hash', 'array']

Metrics/ModuleLength:
  CountAsOne: ['heredoc', 'hash', 'array']

# Rely on ABC complexity for deciding whether a method is too long, not the
# amount of text.
Metrics/MethodLength:
  CountAsOne: ['heredoc', 'hash', 'array']

#TODO:
Metrics/BlockLength:
  CountAsOne: ['heredoc', 'hash', 'array']
  Max: 310
Naming/MethodParameterName:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Capybara/SpecificMatcher:
  Enabled: false
