inherit_gem:
  aaf-gumboot: aaf-rubocop.yml

Style/StderrPuts:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_sql
    - find_by_identifying_attribute

Lint/RescueWithoutErrorClass:
  Exclude:
    - config/initializers/app_config.rb
    - spec/bin/push_events_to_federation_registry_spec.rb

Metrics/BlockLength:
  Exclude:
    - Gemfile
