version: 0.2

phases:
  pre_build:
    commands:
      - echo 'export LANG=en_US.UTF-8' >> ~/.bashrc
      - echo 'export LANGUAGE=en_US.UTF-8' >> ~/.bashrc
      - echo 'export LC_ALL=en_US.UTF-8' >> ~/.bashrc
      - echo 'export AAF_DEV=1' >> ~/.bashrc

      - mysqld_safe & disown -h
      - sleep 5
      - mysql -e "grant all privileges on *.* to 'reporting_app'@'%' identified by 'password';"

      - redis-server & disown -h

      - echo 'export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"' >> ~/.bashrc
      - source ~/.bashrc
      - curl -fsSL https://github.com/rbenv/rbenv-installer/raw/HEAD/bin/rbenv-installer | bash
      - echo 'eval "$(rbenv init -)"' >> ~/.bashrc
      - source ~/.bashrc

      - yum install -y gcc gcc-c++ fontconfig
      - curl -L -o /root/phantomjs-2.1.1-linux-x86_64.tar.bz2 https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
      - tar -jxf /root/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /root
      - echo 'export PATH=$PATH:/root/phantomjs-2.1.1-linux-x86_64/bin' >> ~/.bashrc
      - source ~/.bashrc

      - "[ -e .ruby-version ] && rbenv install $(cat .ruby-version) --skip-existing"
      - gem install bundler
      - bundle install
      - bundle exec torba pack

      - cp config/rapidconnect.yml.dist config/rapidconnect.yml
      - cp config/reporting_service.yml.dist config/reporting_service.yml

      - RAILS_ENV=test bundle exec rake db:reset
  build:
    commands:
      - RAILS_ENV=test bundle exec rake
cache:
  paths:
    - '/root/.rbenv/**/*'
    - '/var/cache/yum/x86_64/7/**/*'
    - 'tmp/**/*'
    - 'schema/**/*'
