default: &default
  adapter: mysql2
  collation: utf8_bin
  encoding: utf8
  host: <%= ENV['REPORTING_DB_HOST'] || '127.0.0.1' %>
  password: "<%= ENV['REPORTING_DB_PASSWORD'] || 'password' %>"
  pool: 5
  port: <%= ENV['REPORTING_DB_PORT'] || 3306 %>
  timeout: 5000
  username: <%= ENV['REPORTING_DB_USERNAME'] || 'reporting_app' %>
development:
  <<: *default
  database: <%= ENV['REPORTING_DB_NAME'] || 'reporting_dev' %>
production:
  <<: *default
  database: <%= ENV['REPORTING_DB_NAME'] || 'reporting_production' %>
test:
  <<: *default
  database: reporting_test
