name: Dependabot automation
on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  issues: write
  repository-projects: write
  contents: write

jobs:
  approve_and_automerge:
    runs-on: ubuntu-latest
    env:
      PR_URL: ${{github.event.pull_request.html_url}}
      GITHUB_TOKEN: ${{secrets.REPO_SCOPED_TOKEN}}
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"

      - name: Get Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.6.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve the PR unless it updates a production dependency
        if: ${{ steps.metadata.outputs.dependency-type != 'direct:production' }}
        run: gh pr review --approve "$PR_URL"
